apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: music-web
spec:
  type: NodePort
  selector:
    app: music-web
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
